# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD$

PORTNAME=	speedtest-cli
PORTVERSION=   	0.3.2
CATEGORIES=     net python
MASTER_SITES=   CHEESESHOP

MAINTAINER=     meta+ports@vmeta.jp
COMMENT=	Command line interface for speedtest.net

LICENSE=	APACHE20

USES=           python:3
USE_PYTHON=     distutils autoplist

.include <bsd.port.mk>
