# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD: ports/devel/rubygem-awesome_print/Makefile,v 1.2 2012/09/29 20:33:43 jase Exp $

PORTNAME=	awesome_print
PORTVERSION=	1.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	Pretty print Ruby objects to visualize their structure

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
