# New ports collection makefile for:	rubygem-awesome_print
# Date created:		2012-05-21
# Whom:			Koichiro IWAO <meta+ports@vmeta.jp>
#
# $FreeBSD: ports/devel/rubygem-awesome_print/Makefile,v 1.1 2012/06/01 15:40:52 swills Exp $
#

PORTNAME=	awesome_print
PORTVERSION=	1.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	Pretty print Ruby objects to visualize their structure

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
