# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD$
PKGNAMESUFFIX=-sjis
COMMENT=        Japanese Morphological Dictionary for MeCab (Shift JIS)

BROKEN=	Does not compile

MASTERDIR=	${.CURDIR}/../mecab-ipadic

.include	"${MASTERDIR}/Makefile.inc"
