# Created by: Koichiro IWAO <meta+ports@vmeta.jpg>
# $FreeBSD$

PORTNAME=	miruo
PORTVERSION=	0.9.5
CATEGORIES=	net
MASTER_SITES=	https://github.com/KLab/miruo/archive/${PORTVERSION}.tar.gz?dummy=/

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	Pretty print TCP session monitor/analizer

LICENSE=	GPLv3

GNU_CONFIGURE=	yes

PLIST_FILES=	sbin/miruo

.include <bsd.port.mk>
