# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD$

PORTNAME=	pluggaloid
PORTVERSION=	1.0.2
CATEGORIES=	rubygems
MASTER_SITES=	RG

MAINTAINER=	meta+ports@vmeta.jp
COMMENT=	Extensible plugin system for mikutter

RUN_DEPENDS=	rubygem-delayer>=0:${PORTSDIR}/devel/rubygem-delayer \
		rubygem-instance_storage>=1.0.0:${PORTSDIR}/devel/rubygem-instance_storage

LICENSE=	MIT

NO_ARCH=	yes
USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
